import type { Config } from 'tailwindcss'

export default {
  content: [
    './app/**/*.{vue,ts,js}',
    './components/**/*.{vue,ts,js}',
    './layouts/**/*.{vue,ts,js}',
    './pages/**/*.{vue,ts,js}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f3f4f2',
        'on-primary-fixed-variant': '#12661e',
        'surface-container': '#eceeec',
        'tertiary-fixed': '#fcfeb9',
        'inverse-surface': '#0c0f0e',
        'surface-container-highest': '#e0e3e1',
        'surface-tint': '#1c6d25',
        'primary-container': '#9df197',
        'tertiary-container': '#fcfeb9',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#60622d',
        'on-surface': '#2f3332',
        'surface-container-high': '#e6e9e6',
        'error': '#a73b21',
        'tertiary-dim': '#545622',
        'secondary-container': '#ffdbcf',
        'tertiary-fixed-dim': '#edefac',
        'on-primary-fixed': '#00460e',
        'on-tertiary': '#fbfdb9',
        'on-tertiary-fixed': '#4d501d',
        'on-secondary': '#fff7f5',
        'on-secondary-fixed-variant': '#775346',
        'outline-variant': '#afb3b0',
        'inverse-on-surface': '#9c9d9c',
        'primary-dim': '#096119',
        'secondary-fixed-dim': '#facab9',
        'surface': '#f9f9f7',
        'on-primary': '#eaffe2',
        'primary-fixed': '#9df197',
        'error-container': '#fd795a',
        'on-primary-container': '#005c15',
        'on-secondary-fixed': '#57382c',
        'surface-variant': '#e0e3e1',
        'background': '#f9f9f7',
        'on-tertiary-container': '#60622d',
        'primary-fixed-dim': '#90e28a',
        'on-background': '#2f3332',
        'on-error-container': '#6e1400',
        'outline': '#777c79',
        'on-secondary-container': '#6c493d',
        'error-dim': '#791903',
        'secondary-fixed': '#ffdbcf',
        'on-tertiary-fixed-variant': '#6a6d37',
        'surface-dim': '#d7dbd8',
        'on-error': '#fff7f6',
        'on-surface-variant': '#5c605e',
        'inverse-primary': '#9df197',
        'secondary-dim': '#6d4b3e',
        'primary': '#1c6d25',
        'secondary': '#7b5749',
        'surface-bright': '#f9f9f7',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
} satisfies Config
